modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ModJNam-Mod/issues"
license="MIT"

[[mods]]
modId="cactusmod"
version="${file.jarVersion}"
displayName="The Cactus Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-cactus-mod"
logoFile="logo.png"
authors="Mrbysco"
description='''
A ModJam 2018.1 mod.
'''
[[dependencies.cactusmod]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.cactusmod]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"